services:
  arch-node:
    image: ghcr.io/arch-network/node:latest
    ports:
      - 9001:9001
    environment:
      LOG_LEVEL: "info" # debug, info, error, warn, trace, off
      RUST_BACKTRACE: "1" # enable error stack traces

      NETWORK_MODE: "testnet" # devnet, testnet, mainnet
      DATA_DIR: "/arch-data" # directory where data will be stored
      PRIVATE_KEY_PASSWORD: "" # Provide a password if you'd like to encrypt the local node keys.
      
      RPC_BIND_IP: "0.0.0.0" # bind to all IPs
      RPC_BIND_PORT: "9001" # TCP 9001

      BITCOIN_RPC_ENDPOINT: "127.0.0.1" # Replace with your bitcoin node's RPC endpoint
      BITCOIN_RPC_PORT: "8443" # Replace with your bitcoin node's RPC port
      BITCOIN_RPC_USERNAME: "" # Replace with your bitcoin node's RPC username (if any)
      BITCOIN_RPC_PASSWORD: "" # Replace with your bitcoin node's RPC password (if any)
      BITCOIN_RPC_WALLET: ""   # Replace with the name of the wallet to be used by arch-node
    volumes:
      - ./arch-data:/arch-data
